#!/usr/bin/env perl

use strict;
use warnings;

my $directory = 'src'; # specify your directory here

# Function to process each .tex file
sub process_file {
    my ($file) = @_;

    open my $fh, '<', $file or die "Cannot open file $file: $!";
    my @lines = <$fh>;
    close $fh;

    my $found_newpage = 0;
    my @modified_lines;

    for my $i (0 .. $#lines) {
        if ($i < 10 && $lines[$i] =~ /\\newpage/) {
            $found_newpage = 1;
            push @modified_lines, $lines[$i], "\\phantomsection\n";
        } else {
            push @modified_lines, $lines[$i];
        }
    }

    if ($found_newpage) {
        open my $out_fh, '>', $file or die "Cannot write to $file: $!";
        print $out_fh @modified_lines;
        close $out_fh;
        print "Updated: $file\n";
    }
}

# Find all .tex files in subdirectories of $directory and process each one
find_files($directory);

sub find_files {
    my ($dir) = @_;

    opendir my $dh, $dir or die "Cannot open directory $dir: $!";
    my @files = grep { -f "$dir/$_" && /\.tex$/ } readdir $dh;
    closedir $dh;

    for my $file (@files) {
        process_file("$dir/$file");
    }

    # Recursively process subdirectories
    opendir $dh, $dir or die "Cannot open directory $dir: $!";
    my @subdirs = grep { -d "$dir/$_" && !/^\.\.?$/ } readdir $dh;
    closedir $dh;

    for my $subdir (@subdirs) {
        find_files("$dir/$subdir");
    }
}

print "Processing complete.\n";

